### ISSUE TITLE
Mobile data loss and 100% loss

### ISSUE THREAD

**Issue by JosiasSena** [pwittchen/ReactiveNetwork#27] opened 2015-10-02 18:22 UTC
Hey man, first off. Thanks for all your hard work. The library is amazing. 

I was using your library and i noticed there is something missing. We cannot check mobile data loss nor can we check 100% loss.

Yes, the library detects if there is no internet (airplane mode) or if we do have internet (Wifi connected, internet available and mobile connected) but it would be nice if the following scenarios could be handled as well:

Mobile data loss: eg user is underground and mobile data is loss. Initially i thought that unknown would be used to handle this but it isnt. I had to do it separately.

Here is a code snippet on how i am currently doing it without the library:

```
/**
 * Determines if there is or if there isnt actual mobile data
 *
 * @return
 */
private boolean hasMobileData() {
    boolean mobileDataEnabled = true; // Assume disabled
    ConnectivityManager cm = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);
    try {
        Class cmClass = Class.forName(cm.getClass().getName());
        Method method = cmClass.getDeclaredMethod("getMobileDataEnabled");
        method.setAccessible(true); // Make the method callable

        // get the setting for "mobile data"
        mobileDataEnabled = (Boolean) method.invoke(cm);
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } catch (NoSuchMethodException e) {
        e.printStackTrace();
    } catch (InvocationTargetException e) {
        e.printStackTrace();
    } catch (IllegalAccessException e) {
        e.printStackTrace();
    }

    Log.e(TAG, "hasMobileData: " + mobileDataEnabled);
    return mobileDataEnabled;
}
```

Also, the other scenario is when we do not have mobile data but we DO have Wifi and it is on 100% packet loss (can be tested using a Network Link Conditioner). This basically means internet is there, we are connected to Wifi but packets are just not coming in.

**Comment by pwittchen** [comment] 2015-10-02 23:25
Thank you for reporting that issue. This library is not designed to handle situations mentioned by you. `UNKOWN` status should be set in case if no status was set already. I think, it shouldn't occur in another situations. You can optionally test your case with `OFFLINE` status.

I'm not sure how to handle your case with mobile data loss and also how to test it properly. I'm not sure if I can reproduce such situation e.g. in a unit test. Code snippet provided by you is quite "hacky" and it uses reflection. I would rather avoid that, because it makes apps slower and is possible source of bugs and Runtime Exceptions.

If you have any idea how to solve this problem in a right way or have any ideas how to test it, your comments (and comments of anyone) are welcome. 

I'll read more about this problem. After gathering more information, it will be easier to solve it.

**Comment by pwittchen** [comment] 2015-10-03 14:24
I think, the right way to solve your problem could be usage of [TelephonyManager](http://developer.android.com/reference/android/telephony/TelephonyManager.html) and [PhoneStateListener](http://developer.android.com/reference/android/telephony/PhoneStateListener.html). It may be an idea for a new project, because this library could become to heavy if we throw everything in it.

**Comment by josias1991** [comment] 2015-10-03 14:59
Thanks for the quick response! 

Sounds good man, just thought it would be worth mentioning it.

Thanks anyways, ill keep on looking into it a bit more and finding the best way to do this in combination with your library.

**Comment by pwittchen** [comment] 2018-07-31 10:56
As we discussed it in #282, this issue should be resolved within a separate project with different responsibilities. I have plans to create another library to address this issue, but I need to find a time for that. This issue can be closed for now.

**Closed by pwittchen** 2018-07-31 10:56 UTC
Labels: discussion
