### ISSUE TITLE
In demo, if I click back button to quit, then it won't work next time

### ISSUE THREAD

**Issue by hcjcch** [pwittchen/ReactiveNetwork#31] opened 2015-10-19 08:03 UTC
I think `private static ConnectivityStatus status = ConnectivityStatus.UNKNOWN;` should be changed to `private ConnectivityStatus status = ConnectivityStatus.UNKNOWN;`

**Comment by pwittchen** [comment] 2015-10-19 09:22
Can you explain, what do you mean by "no work"? Application crashed or it wasn't reacting on connectivity changes? Do you have any LogCat output, which can help to find source of the potential problem?

In `ReactiveNetwork` class, `status` attribute is static, because I wanted to have a single instance of `ConnectivityStatus`, which could be used to verify if status changed or not after receiving an event in BroadcastReceiver. The reason of that is the fact that I encountered situations in which status was emitted two times when single event occurred.

**Comment by pwittchen** [comment] 2015-10-19 18:17
I'll test it and try to reproduce this bug.

**Comment by hcjcch** [comment] 2015-10-20 02:51
```
if (newStatus != status) {
          status = newStatus;
          subscriber.onNext(newStatus);
 }
```
The `status` is static ,if you quit the application(not kill),the `status`will keep the last time the value.If your network status not change,`newStatus != status` will false ,and `tvConnectivityStatus`will always show `Waiting for connectivity status` until your network status be changed.

**Comment by pwittchen** [comment] 2015-10-20 07:24
Thank you. This explanation is quite clear. I'll try to reproduce it. If your suggestion is right, it may be quick fix.

**Comment by pwittchen** [comment] 2015-11-02 22:30
I was able to reproduce this bug. It's fixed in https://github.com/pwittchen/ReactiveNetwork/commit/f34a53c8f52256b24534b88d17cc0db0930dcfa8. I'm sorry that you had to wait so long for such simple change. Fortunately, I found a moment to take a look at this issue.

This fix will be available in the next release.

**Closed by pwittchen** 2015-11-02 22:30 UTC
Labels: bug
