### ISSUE TITLE
leaked IntentReceiver 

### ISSUE THREAD

**Issue by eslam2010011** [pwittchen/ReactiveNetwork#427] opened 2020-04-03 15:55 UTC
use android 9

2020-04-03 17:15:28.355 27914-27914/com.opyapp E/ActivityThread: Activity com.opyapp.ui.Activity.Home.MainActivity has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$4@79be023 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.opyapp.ui.Activity.Home.MainActivity has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$4@79be023 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1560)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1271)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1502)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1475)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1463)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:634)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.registerIdleReceiver(MarshmallowNetworkObservingStrategy.java:116)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.observeNetworkConnectivity(MarshmallowNetworkObservingStrategy.java:73)
        at com.github.pwittchen.reactivenetwork.library.rx2.ReactiveNetwork.observeNetworkConnectivity(ReactiveNetwork.java:92)
        at com.github.pwittchen.reactivenetwork.library.rx2.ReactiveNetwork.observeNetworkConnectivity(ReactiveNetwork.java:73)
        at com.opyapp.utils.NetworkUtils.getforyou(NetworkUtils.java:130)
        at com.opyapp.ui.Activity.Home.Fragment.Discover.DiscoverFragment.onCreateView(DiscoverFragment.java:61)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23634)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1187)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:706)
        at android.view.View.measure(View.java:23634)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23634)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23634)
    	at android.view.Vie

**Comment by pwittchen** [comment] 2020-04-03 17:38
Thanks for reporting this. It's duplicate of #419.

**Closed as completed by pwittchen** 2020-04-03 17:38 UTC
Labels: duplicate

**Comment by eslam2010011** [comment] 2020-04-03 17:52
Thank you for this great library but how do you fix this

**Comment by pwittchen** [comment] 2020-04-03 23:02
Please follow this problem in #419 issue. Right now, I don't know how to fix this issue. If you can provide steps to reproduce this problem, it will be helpful to diagnose the issue. Moreover, please make sure that you disposed your observables appropriately (e.g. in onPause() method) because this problem may be caused by this.
