### ISSUE TITLE
Switching off Wifi yields false positive DISCONNECTED

### ISSUE THREAD

**Issue by Bombo** [pwittchen/ReactiveNetwork#170] opened 2017-04-26 16:43 UTC
First of all I think this is a really great library and I'd really want to use it in our app. Unfortunately I've found an issue while playing around with it on my Sony Xperia Z2 running Android 6.0.1. The issue is also reproducible for me with the supplied java test app:
![screenshot](https://cloud.githubusercontent.com/assets/224092/25445896/f7fc16d2-2aaf-11e7-8487-16f3d8d13a52.jpg)

There have actually been instances where it worked. I guess mostly on a fresh app start and switching off Wifi for the first time, but after that I got stuck at a `DISCONNECTED` state, where typeName sometimes states `NONE` and sometimes `MOBILE`

**Comment by pwittchen** [comment] 2017-04-26 17:09
Hi,

Thanks for reporting this issue. Can you provide exact steps to reproduce that problem?

**Comment by Bombo** [comment] 2017-04-26 17:23
Sure.

1. Built and deployed app module on my device
2. Open the app while connected via wifi.
3. Pull down notification area and switch off wifi
4. Close notification area
5. Result is as in screenshot

I'm afraid that's all I have. I just now noticed when there is a small delay between losing wifi and connecting to the mobile network it seems to recover. Of course there is a short time where it's disconnected and then correctly reconnects. So this might only occur if the switch is instantaneously? Maybe some kind of race-condition.

**Comment by pwittchen** [comment] 2017-04-26 17:28
It looks like the app is switching from one type of the connection (wifi) to another (mobile). Maybe this situation happens in short period of time during such switch. I'll take a look on that, but it may be an issue, which is not exactly related to the library itself, but the system behavior.

**Comment by Bombo** [comment] 2017-04-28 08:58
Yes, that's what I was thinking. I will look into this myself, if I get the time. Thanks!

**Comment by kmalmur** [comment] 2017-12-12 08:16
the same on my side. @Bombo how did you deal with that?

**Comment by Bombo** [comment] 2017-12-12 08:22
@kmalmur I haven't, yet. I switched to a [different library](https://github.com/novoda/merlin) for now.

**Comment by waniolka** [comment] 2017-12-17 13:57
Same error on Xiaomi Mi6.

**Comment by pwittchen** [comment] 2017-12-17 16:12
@Bombo @kmalmur @waniolka Can you provide any concrete steps, details or conditions to reproduce this bug? I'm using Motorola Nexus 6 with clean Android 7.1.1 and I cannot reproduce it, so I cannot figure out the source of that bug. Now it looks like it's device specific or related to the concrete Android OS version.

**Comment by kmalmur** [comment] 2017-12-17 16:18
It happens right after I turn off the WiFi, and the phone switches to
Mobile data.

17.12.2017 5:12 PM "Piotr Wittchen" <notifications@github.com> napisał(a):

**Comment by hollmannlu** [comment] 2018-03-15 15:47
Same here, v0.12.3
Pixel with 8.1 and Nexus 5x with 8.1

I am starting the app with turned on wifi:
`Connectivity{state=CONNECTED, detailedState=CONNECTED, type=9, subType=0, available=true, failover=false, roaming=false, typeName='Ethernet', subTypeName='', reason='null', extraInfo='08:00:27:85:55:66'}`

 then I turn off wifi and instead of stating a mobile-connection it states:
`Connectivity{state=DISCONNECTED, detailedState=DISCONNECTED, type=1, subType=0, available=true, failover=false, roaming=false, typeName='WIFI', subTypeName='', reason='null', extraInfo='<unknown ssid>'}`

I am using `ReactiveNetwork.observeNetworkConnectivity(mContext)`

When I start just with the mobile connection it works...

**Comment by herberthartkor** [comment] 2018-04-30 07:34
Hi!
Any updates on this? I've got the same issues and can verify the last comment.

**Comment by Kisty** [comment] 2018-05-01 05:55
@herberthartkor please see the above comment https://github.com/pwittchen/ReactiveNetwork/issues/170#issuecomment-352266454

**Comment by pwittchen** [comment] 2018-07-31 10:53
This issue was resolved in #276. 

References:
- comment: https://github.com/pwittchen/ReactiveNetwork/issues/276#issuecomment-396147241
- commit in the documentation: https://github.com/pwittchen/ReactiveNetwork/commit/76ab2b23210207d83250da5d8fd0cd6e275e3f08

In case of any further problems, you re-open this issue or create a new one.

**Closed as completed by pwittchen** 2018-07-31 10:53 UTC
Labels: bug
