### ISSUE TITLE
RN tries to check via IPv6 on some devices and fails

### ISSUE THREAD

**Issue by intari** [pwittchen/ReactiveNetwork#286] opened 2018-07-19 02:25 UTC
I use ReactiveNetwork in this way:

```java 
InternetObservingSettings globalSettings = InternetObservingSettings
                .host("https://www.google.com")
                .strategy(strategy)
                .build();

        ReactiveNetwork
                .observeInternetConnectivity(globalSettings)
                //.flatMapSingle(connectivity -> ReactiveNetwork.checkInternetConnectivity())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(isConnected -> {
                    // isConnected can be true or false
                    CustomLog.i(TAG,"Connected to Global Internet:"+isConnected);
                    mCanReachGlobal =isConnected;
                });
```
It has to be https to prevent issues with captive portals like one from wi-fi.ru  

Some devices like Asus ZenFone Max Pro (M1) ZB602KL (Android 8.1) keep getting 

```
E/ReactiveNetwork: Could not establish connection with WalledGardenStrategy
                   java.net.SocketTimeoutException: failed to connect to www.google.com/2a00:1450:400e:806::2004 (port 80) from /fec0::60cd:f983:4b96:9cd0 (port 54962) after 2000ms
```

in logcat.
Local WiFi doesn't provide IPv6. Cellular operator also doesn't provide it but RN tries to connect via IPv6 and fails.

**Comment by pwittchen** [comment] 2018-07-19 06:18
Hi,

It's strange. Does it happen on this device only? If yes, then I suppose it may be its hardware specific issue. You can also try another available strategy for observing Internet connection: `SocketInternetObservingStrategy` instead of `WalledGardenInternetObservingStrategy` (default) and check if anything changes. You can set it via `InternetObservingSettings` builder.

Regards,
Piotr

**Comment by intari** [comment] 2018-07-19 07:07
hi,
Yes, this device only so far.
SocketInternetConnection helps.

**Comment by pwittchen** [comment] 2018-07-19 08:21
Great that this solution helps!

czw., 19 lip 2018, 09:07 użytkownik Dmitriy Kazimirov <
notifications@github.com> napisał:

**Comment by pwittchen** [comment] 2018-07-19 21:36
Ok. I see the problem is solved, so we can close this issue.

**Closed as completed by pwittchen** 2018-07-19 21:36 UTC
